name = "5mns"
compatibility_date = "2024-11-20"

# 👇 tell wrangler where CRA outputs static files
pages_build_output_dir = "build"

[vars]
ADMIN_TOKEN = "choose-a-long-secret"

[[d1_databases]]
binding = "DB"
database_name = "5mns-db"
database_id = "c07c6b33-0e6c-466d-bae5-d928af3f73f0"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "5mns-bucket"
